

test:
  bool: 0
  int: 2000
  uint: 4000
  double: 2.33
  float: 222
  string: TRUEWss
  vector.int: [1,3,4,5,6]
  list.int:
    - 2
    - 3
    - 5
    - 6
  set.int: [1,3,4,5,5,6,6]
  unordered_set.int: [2,3,4,55,66,44,4]
  map.int:
    a: 65
    b: 66
    c: 67
  unordered_map.int:
    a: 65
    b: 66
    c: 67

testlog:
  name: "testlog"
  level: "debug"
  formatter: "%D%T%t%P%c%m%N%n"
  appenders:
    - type :  "fileappender"
      path :  "outlog.txt"
      level : "debug"
    - type : "consoleappender"
      level : "debug"

